### ISSUE TITLE
Format of query in Search Module 

### ISSUE THREAD

**Issue by r0b78** [philleepflorence/directus-8-extensions#4]
![image](https://user-images.githubusercontent.com/22716876/77135144-cd624c80-6a2f-11ea-9633-b3d9e8c6b95e.png)
 The format of the query in the client is only
` {query: "any text"}`
donsn't have the collections field

**Comment by philleepflorence** [comment]
Are you trying to use the Search Database Function?

If you do not specify the collection, then the search will run through all non-directus collections.

**Comment by r0b78** [comment]
the query work for me when i do 
{query:'aaa', collections:[collection1, collection2]}

but with out didn't work 
I wot in to this part and the fields still empty 
![image](https://user-images.githubusercontent.com/22716876/77221648-12aa7b00-6b11-11ea-9b84-50d00dcbe0d5.png)

Thanks for the reply
