### ISSUE TITLE
Filter of custom interfaces unclear

### ISSUE THREAD

**Issue by MajesteitBart** [philleepflorence/directus-8-extensions#5]
This probably isn't an issue with the interfaces, as much as documentation. But to me it's unclear on how the filter of interfaces work. Is it possible to provide an example for the dropdown extended and Many to One extended fields. 

I'd imagine it would only show records that are filtered by another field in the item:

Field 1 (checkbox) - Company industry:
- Agri
- Industrial 
- **Services**

Field 2: (dropdown ext) Select a sub-industry 

- IT services
- Financial services
- etc.

Is this possible with these interfaces?

**Comment by philleepflorence** [comment]
I am still in the process of developing the extensions and will write a doc once Directus v9 App is released.
I might also write a blog post on this soon.
***
In the meantime: It is possible with a few tweaks.

You can have the second interface watch the **checkbox** interface for changes and update it's data accordingly.
You would need to combine the core **slug** interface below...
```
<template>
...
</template>

<script>
import slug from 'slug';
import mixin from '@directus/extension-toolkit/mixins/interface';
export default {
	mixins: [mixin],
	computed: {
		mirror() {
			const { mirroredField } = this.options;
			return this.values[mirroredField];
		},
		disabled() {
			if (this.readonly === true) return true;
			if (this.options.onlyOnCreate === true && this.newItem === false) return true;
			return false;
		}
	},
	watch: {
		mirror() {
			this.updateValue(this.mirror);
		}
	},
	methods: {
		updateValue(value) {
			if (this.disabled) return;
			this.$emit(
				'input',
				slug(value, {
					lower: this.options.forceLowercase
				})
			);
		}
	}
};
</script>

<style lang="scss" scoped>
...
</style>
```
...with an interface like the **many-to-one-extended** interface.

The checkbox will emit its value on mounted and on change and the many-to-one-extended will then watch for changes and run the **fetchItems** method updating its filters.

**Comment by MajesteitBart** [comment]
That's awesome, thank you so much!
